project_id = "otezimmvabqgbcrouglw"

[api]
enabled = true
max_rows = 1000

[db]
major_version = 17

[realtime]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:8080"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_confirmations = false

[storage]
enabled = true
file_size_limit = "50MiB"

[functions.predict-match]
verify_jwt = true

[functions.fetch-sports-data]
verify_jwt = false

[functions.refresh-live-data]
verify_jwt = false

[analytics]
enabled = false
