INSERT INTO public.teams (name, sport, league, country)
VALUES
('AS Roma', 'football', 'FOOTBALL SCHEDULE', NULL),
('AmaZulu FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('AmaZulu Reserves', 'football', 'FOOTBALL SCHEDULE', NULL),
('Arsenal', 'football', 'FOOTBALL SCHEDULE', NULL),
('Aston Villa', 'football', 'FOOTBALL SCHEDULE', NULL),
('Atalanta', 'football', 'FOOTBALL SCHEDULE', NULL),
('Australia Women', 'cricket', 'CRICKET SCHEDULE', NULL),
('Auxerre', 'football', 'FOOTBALL SCHEDULE', NULL),
('Baroka FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('Benetton Rugby', 'rugby', 'RUGBY SCHEDULE', NULL),
('Bologna', 'football', 'FOOTBALL SCHEDULE', NULL),
('Bournemouth', 'football', 'FOOTBALL SCHEDULE', NULL),
('Brentford', 'football', 'FOOTBALL SCHEDULE', NULL),
('Brest', 'football', 'FOOTBALL SCHEDULE', NULL),
('Brighton', 'football', 'FOOTBALL SCHEDULE', NULL),
('Bristol City', 'football', 'FOOTBALL SCHEDULE', NULL),
('Bulls', 'rugby', 'RUGBY SCHEDULE', NULL),
('Burnley', 'football', 'FOOTBALL SCHEDULE', NULL),
('CSA Emerging', 'cricket', 'CRICKET SCHEDULE', NULL),
('CUT', 'rugby', 'RUGBY SCHEDULE', NULL),
('Cape Town City FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('Cardiff Rugby', 'rugby', 'RUGBY SCHEDULE', NULL),
('Casric Stars', 'football', 'FOOTBALL SCHEDULE', NULL),
('Celta Vigo', 'football', 'FOOTBALL SCHEDULE', NULL),
('Chelsea', 'football', 'FOOTBALL SCHEDULE', NULL),
('Chippa United', 'football', 'FOOTBALL SCHEDULE', NULL),
('Chippa United Reserves', 'football', 'FOOTBALL SCHEDULE', NULL),
('Connacht', 'rugby', 'RUGBY SCHEDULE', NULL),
('Crystal Palace', 'football', 'FOOTBALL SCHEDULE', NULL),
('DP World Lions', 'cricket', 'CRICKET SCHEDULE', NULL),
('Dafabet Warriors', 'cricket', 'CRICKET SCHEDULE', NULL),
('Dragons', 'rugby', 'RUGBY SCHEDULE', NULL),
('Durban City', 'football', 'FOOTBALL SCHEDULE', NULL),
('Eastern Cape Iinyathi', 'cricket', 'CRICKET SCHEDULE', NULL),
('Eastern Storm', 'cricket', 'CRICKET SCHEDULE', NULL),
('Edinburgh', 'rugby', 'RUGBY SCHEDULE', NULL),
('Emeris', 'rugby', 'RUGBY SCHEDULE', NULL),
('England Men', 'rugby', 'RUGBY SCHEDULE', NULL),
('Everton', 'football', 'FOOTBALL SCHEDULE', NULL),
('Fiorentina', 'football', 'FOOTBALL SCHEDULE', NULL),
('Flexbrands Knights', 'cricket', 'CRICKET SCHEDULE', NULL),
('France Men', 'rugby', 'RUGBY SCHEDULE', NULL),
('Fulham', 'football', 'FOOTBALL SCHEDULE', NULL),
('Getafe', 'football', 'FOOTBALL SCHEDULE', NULL),
('Girona', 'football', 'FOOTBALL SCHEDULE', NULL),
('Glasgow Warriors', 'rugby', 'RUGBY SCHEDULE', NULL),
('Golden Arrows', 'football', 'FOOTBALL SCHEDULE', NULL),
('Golden Arrows Reserves', 'football', 'FOOTBALL SCHEDULE', NULL),
('Goldrush Boland', 'cricket', 'CRICKET SCHEDULE', NULL),
('Hollywoodbets Dolphins', 'cricket', 'CRICKET SCHEDULE', NULL),
('India Men', 'cricket', 'CRICKET SCHEDULE', NULL),
('India Women', 'cricket', 'CRICKET SCHEDULE', NULL),
('Ireland Men', 'rugby', 'RUGBY SCHEDULE', NULL),
('Italy Men', 'rugby', 'RUGBY SCHEDULE', NULL),
('Juventus', 'football', 'FOOTBALL SCHEDULE', NULL),
('Kaizer Chiefs', 'football', 'FOOTBALL SCHEDULE', NULL),
('LOSC Lille', 'football', 'FOOTBALL SCHEDULE', NULL),
('Leeds United', 'football', 'FOOTBALL SCHEDULE', NULL),
('Leinster', 'rugby', 'RUGBY SCHEDULE', NULL),
('Lerumo Lions', 'football', 'FOOTBALL SCHEDULE', NULL),
('Limpopo Impalas', 'cricket', 'CRICKET SCHEDULE', NULL),
('Lions', 'rugby', 'RUGBY SCHEDULE', NULL),
('Liverpool', 'football', 'FOOTBALL SCHEDULE', NULL),
('Llanelli Scarlets', 'rugby', 'RUGBY SCHEDULE', NULL),
('Lorient', 'football', 'FOOTBALL SCHEDULE', NULL),
('Magesi FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('Mamelodi Sundowns', 'football', 'FOOTBALL SCHEDULE', NULL),
('Mamelodi Sundowns Reserves', 'football', 'FOOTBALL SCHEDULE', NULL),
('Manchester City', 'football', 'FOOTBALL SCHEDULE', NULL),
('Manchester United', 'football', 'FOOTBALL SCHEDULE', NULL),
('Marseille', 'football', 'FOOTBALL SCHEDULE', NULL),
('Marumo Gallants', 'football', 'FOOTBALL SCHEDULE', NULL),
('Maties', 'rugby', 'RUGBY SCHEDULE', NULL),
('Metz', 'football', 'FOOTBALL SCHEDULE', NULL),
('Momentum Multiply Titans', 'cricket', 'CRICKET SCHEDULE', NULL),
('Monaco', 'football', 'FOOTBALL SCHEDULE', NULL),
('Mpumalanga Rhinos', 'cricket', 'CRICKET SCHEDULE', NULL),
('Munster', 'rugby', 'RUGBY SCHEDULE', NULL),
('NWU', 'rugby', 'RUGBY SCHEDULE', NULL),
('Nantes', 'football', 'FOOTBALL SCHEDULE', NULL),
('Napoli', 'football', 'FOOTBALL SCHEDULE', NULL),
('New Zealand Men', 'cricket', 'CRICKET SCHEDULE', NULL),
('Newcastle', 'football', 'FOOTBALL SCHEDULE', NULL),
('Nice', 'football', 'FOOTBALL SCHEDULE', NULL),
('North West Dragons', 'cricket', 'CRICKET SCHEDULE', NULL),
('Northern Cape Heat', 'cricket', 'CRICKET SCHEDULE', NULL),
('Nottingham Forest', 'football', 'FOOTBALL SCHEDULE', NULL),
('Olympique Lyonnais', 'football', 'FOOTBALL SCHEDULE', NULL),
('Orbit College FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('Orlando Pirates', 'football', 'FOOTBALL SCHEDULE', NULL),
('Orlando Pirates Reserves', 'football', 'FOOTBALL SCHEDULE', NULL),
('Osasuna', 'football', 'FOOTBALL SCHEDULE', NULL),
('Ospreys', 'rugby', 'RUGBY SCHEDULE', NULL),
('Paris FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('Paris Saint-Germain', 'football', 'FOOTBALL SCHEDULE', NULL),
('Pisa', 'football', 'FOOTBALL SCHEDULE', NULL),
('Polokwane City', 'football', 'FOOTBALL SCHEDULE', NULL),
('Port Vale', 'football', 'FOOTBALL SCHEDULE', NULL),
('Pretoria University FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('Rayo Vallecano', 'football', 'FOOTBALL SCHEDULE', NULL),
('Real Betis', 'football', 'FOOTBALL SCHEDULE', NULL),
('Real Madrid', 'football', 'FOOTBALL SCHEDULE', NULL),
('Real Oviedo', 'football', 'FOOTBALL SCHEDULE', NULL),
('Richards Bay', 'football', 'FOOTBALL SCHEDULE', NULL),
('SS Lazio', 'football', 'FOOTBALL SCHEDULE', NULL),
('Sassuolo', 'football', 'FOOTBALL SCHEDULE', NULL),
('Scotland Men', 'rugby', 'RUGBY SCHEDULE', NULL),
('Sekhukhune United', 'football', 'FOOTBALL SCHEDULE', NULL),
('Sekhukhune United Reserves', 'football', 'FOOTBALL SCHEDULE', NULL),
('Sevilla', 'football', 'FOOTBALL SCHEDULE', NULL),
('Sharks', 'rugby', 'RUGBY SCHEDULE', NULL),
('Shimlas', 'rugby', 'RUGBY SCHEDULE', NULL),
('Siwelele', 'football', 'FOOTBALL SCHEDULE', NULL),
('Six Gun Grill Garden Route Badgers', 'cricket', 'CRICKET SCHEDULE', NULL),
('South Africa Men', 'cricket', 'CRICKET SCHEDULE', NULL),
('Stellenbosch FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('Stormers', 'rugby', 'RUGBY SCHEDULE', NULL),
('Sunderland', 'football', 'FOOTBALL SCHEDULE', NULL),
('TS Galaxy', 'football', 'FOOTBALL SCHEDULE', NULL),
('Torino', 'football', 'FOOTBALL SCHEDULE', NULL),
('Tottenham Hotspur', 'football', 'FOOTBALL SCHEDULE', NULL),
('Tuskers', 'cricket', 'CRICKET SCHEDULE', NULL),
('UCT Ikeys', 'rugby', 'RUGBY SCHEDULE', NULL),
('UJ', 'rugby', 'RUGBY SCHEDULE', NULL),
('UP-Tuks', 'rugby', 'RUGBY SCHEDULE', NULL),
('Udinese', 'football', 'FOOTBALL SCHEDULE', NULL),
('Ulster', 'rugby', 'RUGBY SCHEDULE', NULL),
('Valencia', 'football', 'FOOTBALL SCHEDULE', NULL),
('WSB Western Province', 'cricket', 'CRICKET SCHEDULE', NULL),
('Wales Men', 'rugby', 'RUGBY SCHEDULE', NULL),
('West Ham', 'football', 'FOOTBALL SCHEDULE', NULL),
('Wolves', 'football', 'FOOTBALL SCHEDULE', NULL),
('Zebre', 'rugby', 'RUGBY SCHEDULE', NULL)
ON CONFLICT (name)
DO UPDATE SET
  sport = EXCLUDED.sport,
  league = EXCLUDED.league,
  country = COALESCE(EXCLUDED.country, public.teams.country);