INSERT INTO public.teams (name, sport, league, country)
VALUES
('AS Roma', 'football', 'FOOTBALL SCHEDULE', NULL),
('AmaZulu FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('AmaZulu Reserves', 'football', 'FOOTBALL SCHEDULE', NULL),
('Arsenal', 'football', 'FOOTBALL SCHEDULE', NULL),
('Aston Villa', 'football', 'FOOTBALL SCHEDULE', NULL),
('Atalanta', 'football', 'FOOTBALL SCHEDULE', NULL),
('Auxerre', 'football', 'FOOTBALL SCHEDULE', NULL),
('Baroka FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('Bologna', 'football', 'FOOTBALL SCHEDULE', NULL),
('Bournemouth', 'football', 'FOOTBALL SCHEDULE', NULL),
('Brentford', 'football', 'FOOTBALL SCHEDULE', NULL),
('Brest', 'football', 'FOOTBALL SCHEDULE', NULL),
('Brighton', 'football', 'FOOTBALL SCHEDULE', NULL),
('Bristol City', 'football', 'FOOTBALL SCHEDULE', NULL),
('Burnley', 'football', 'FOOTBALL SCHEDULE', NULL),
('Cape Town City FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('Casric Stars', 'football', 'FOOTBALL SCHEDULE', NULL),
('Celta Vigo', 'football', 'FOOTBALL SCHEDULE', NULL),
('Chelsea', 'football', 'FOOTBALL SCHEDULE', NULL),
('Chippa United', 'football', 'FOOTBALL SCHEDULE', NULL),
('Chippa United Reserves', 'football', 'FOOTBALL SCHEDULE', NULL),
('Crystal Palace', 'football', 'FOOTBALL SCHEDULE', NULL),
('Durban City', 'football', 'FOOTBALL SCHEDULE', NULL),
('Everton', 'football', 'FOOTBALL SCHEDULE', NULL),
('Fiorentina', 'football', 'FOOTBALL SCHEDULE', NULL),
('Fulham', 'football', 'FOOTBALL SCHEDULE', NULL),
('Getafe', 'football', 'FOOTBALL SCHEDULE', NULL),
('Girona', 'football', 'FOOTBALL SCHEDULE', NULL),
('Golden Arrows', 'football', 'FOOTBALL SCHEDULE', NULL),
('Golden Arrows Reserves', 'football', 'FOOTBALL SCHEDULE', NULL),
('Juventus', 'football', 'FOOTBALL SCHEDULE', NULL),
('Kaizer Chiefs', 'football', 'FOOTBALL SCHEDULE', NULL),
('LOSC Lille', 'football', 'FOOTBALL SCHEDULE', NULL),
('Leeds United', 'football', 'FOOTBALL SCHEDULE', NULL),
('Lerumo Lions', 'football', 'FOOTBALL SCHEDULE', NULL),
('Liverpool', 'football', 'FOOTBALL SCHEDULE', NULL),
('Lorient', 'football', 'FOOTBALL SCHEDULE', NULL),
('Magesi FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('Mamelodi Sundowns', 'football', 'FOOTBALL SCHEDULE', NULL),
('Mamelodi Sundowns Reserves', 'football', 'FOOTBALL SCHEDULE', NULL),
('Manchester City', 'football', 'FOOTBALL SCHEDULE', NULL),
('Manchester United', 'football', 'FOOTBALL SCHEDULE', NULL),
('Marseille', 'football', 'FOOTBALL SCHEDULE', NULL),
('Marumo Gallants', 'football', 'FOOTBALL SCHEDULE', NULL),
('Metz', 'football', 'FOOTBALL SCHEDULE', NULL),
('Monaco', 'football', 'FOOTBALL SCHEDULE', NULL),
('Nantes', 'football', 'FOOTBALL SCHEDULE', NULL),
('Napoli', 'football', 'FOOTBALL SCHEDULE', NULL),
('Newcastle', 'football', 'FOOTBALL SCHEDULE', NULL),
('Nice', 'football', 'FOOTBALL SCHEDULE', NULL),
('Nottingham Forest', 'football', 'FOOTBALL SCHEDULE', NULL),
('Olympique Lyonnais', 'football', 'FOOTBALL SCHEDULE', NULL),
('Orbit College FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('Orlando Pirates', 'football', 'FOOTBALL SCHEDULE', NULL),
('Orlando Pirates Reserves', 'football', 'FOOTBALL SCHEDULE', NULL),
('Osasuna', 'football', 'FOOTBALL SCHEDULE', NULL),
('Paris FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('Paris Saint-Germain', 'football', 'FOOTBALL SCHEDULE', NULL),
('Pisa', 'football', 'FOOTBALL SCHEDULE', NULL),
('Polokwane City', 'football', 'FOOTBALL SCHEDULE', NULL),
('Port Vale', 'football', 'FOOTBALL SCHEDULE', NULL),
('Pretoria University FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('Rayo Vallecano', 'football', 'FOOTBALL SCHEDULE', NULL),
('Real Betis', 'football', 'FOOTBALL SCHEDULE', NULL),
('Real Madrid', 'football', 'FOOTBALL SCHEDULE', NULL),
('Real Oviedo', 'football', 'FOOTBALL SCHEDULE', NULL),
('Richards Bay', 'football', 'FOOTBALL SCHEDULE', NULL),
('SS Lazio', 'football', 'FOOTBALL SCHEDULE', NULL),
('Sassuolo', 'football', 'FOOTBALL SCHEDULE', NULL),
('Sekhukhune United', 'football', 'FOOTBALL SCHEDULE', NULL),
('Sekhukhune United Reserves', 'football', 'FOOTBALL SCHEDULE', NULL),
('Sevilla', 'football', 'FOOTBALL SCHEDULE', NULL),
('Siwelele', 'football', 'FOOTBALL SCHEDULE', NULL),
('Stellenbosch FC', 'football', 'FOOTBALL SCHEDULE', NULL),
('Sunderland', 'football', 'FOOTBALL SCHEDULE', NULL),
('TS Galaxy', 'football', 'FOOTBALL SCHEDULE', NULL),
('Torino', 'football', 'FOOTBALL SCHEDULE', NULL),
('Tottenham Hotspur', 'football', 'FOOTBALL SCHEDULE', NULL),
('Udinese', 'football', 'FOOTBALL SCHEDULE', NULL),
('Valencia', 'football', 'FOOTBALL SCHEDULE', NULL),
('West Ham', 'football', 'FOOTBALL SCHEDULE', NULL),
('Wolves', 'football', 'FOOTBALL SCHEDULE', NULL)
ON CONFLICT (name)
DO UPDATE SET
  sport = EXCLUDED.sport,
  league = EXCLUDED.league,
  country = COALESCE(EXCLUDED.country, public.teams.country);